#!/usr/bin/env python3
"""
generate_vale_rules.py

LAYER 1 generator. Reads product-registry.yaml (the single source of truth)
and writes out Vale style files. Never hand-edit the generated files —
re-run this script instead. Run this before every scan (that's what `make
rules` is for once the Makefile exists).

Generates:
  vale/styles/COSGrid/ProductNames.yml   (substitution rules, error)
  vale/styles/COSGrid/Provisional.yml    (existence rules, warning)
  vale/styles/COSGrid/BrandRules.yml     (existence rules, error)
  vale/.vale.ini                         (base config)

Usage:
    python3 generate_vale_rules.py --registry product-registry.yaml --out vale/
"""

import argparse
import sys
from pathlib import Path

import yaml


HEADER = "# GENERATED by generate_vale_rules.py — do not hand-edit. Edit product-registry.yaml instead.\n"


def load_registry(path):
    with open(path, "r", encoding="utf-8") as f:
        return yaml.safe_load(f)


def build_substitution_style(registry):
    """
    One entry per forbidden->canonical pair, across all non-provisional
    products. This is what catches 'Qshield' -> suggest 'QShield',
    'RefleXion SD-WAN' -> suggest 'ReFleX-WAN', etc.
    """
    swap = {}
    for key, entry in registry.get("products", {}).items():
        if entry.get("status") == "provisional":
            continue
        canonical = entry.get("canonical")
        if not canonical:
            continue
        for forbidden in entry.get("forbidden", []) or []:
            swap[forbidden] = canonical

    company = registry.get("brand", {}).get("company", {})
    # Company name handled separately (warning-level, see BrandRules)

    doc = {
        "extends": "substitution",
        "message": "Use the canonical name '%s' instead of '%s'.",
        "level": "error",
        "ignorecase": False,
        "swap": swap,
    }
    return doc


def build_provisional_style(registry):
    """
    Products marked status: provisional -> warning, not error. Also any
    products missing entirely from the 'forbidden' regeneration above but
    explicitly flagged provisional get a light-touch existence check on
    common misspellings if provided.
    """
    tokens = []
    for key, entry in registry.get("products", {}).items():
        if entry.get("status") == "provisional":
            for forbidden in entry.get("forbidden", []) or []:
                tokens.append(forbidden)

    doc = {
        "extends": "existence",
        "message": "'%s' relates to a provisional product name — confirm this is still correct before publishing.",
        "level": "warning",
        "ignorecase": False,
        "tokens": tokens if tokens else ["___placeholder_no_provisional_terms___"],
    }
    return doc


def build_brand_rules_style(registry):
    """
    Brand-level global_rules (e.g. forbid VPN/movpn in public content) plus
    the company name interim rule (warning, not error, per the plan's
    'warn-only until Sep-2026 rename review' decision).

    NOTE: Vale's `existence` rule does not natively support the registry's
    `allow_in` glob exemptions or `scope: public` per-rule. Enforce those by
    scoping this style's activation in .vale.ini to only the directories
    listed under `scope: public` (content/, social/, email/, campaigns/),
    and by NOT applying this style to allow_in paths such as
    competitive-analysis/ or *battlecard* — do that via a second [format]
    section in .vale.ini that excludes this style for those globs.
    """
    tokens = []
    brand = registry.get("brand", {})

    for rule in brand.get("global_rules", []) or []:
        for forbidden in rule.get("forbid", []) or []:
            tokens.append(forbidden)

    doc_error = {
        "extends": "existence",
        "message": "'%s' is not allowed in public-facing content — see product-registry.yaml global_rules.",
        "level": "error",
        "ignorecase": False,
        "tokens": tokens if tokens else ["___placeholder_no_brand_terms___"],
    }

    company = brand.get("company", {})
    company_tokens = company.get("forbidden", []) or []
    doc_warning = {
        "extends": "existence",
        "message": "'%s' — company name interim rule: warn-only until the Sep-2026 rename review.",
        "level": "warning",
        "ignorecase": False,
        "tokens": company_tokens if company_tokens else ["___placeholder_no_company_terms___"],
    }

    return doc_error, doc_warning


def write_yaml(path, doc):
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write(HEADER)
        yaml.dump(doc, f, default_flow_style=False, sort_keys=False, allow_unicode=True)


def write_vale_ini(out_dir, content_dirs, allow_in_globs):
    """
    Base .vale.ini. Scoped to markdown/html/mdx by default. allow_in globs
    from the registry are surfaced here as a comment + a best-effort
    [format] override that turns the BrandRules style off for those paths —
    Vale evaluates sections top-to-bottom and later sections override
    earlier ones for matching files.
    """
    ini_path = out_dir / ".vale.ini"
    lines = []
    lines.append("# GENERATED by generate_vale_rules.py — do not hand-edit.")
    lines.append("StylesPath = styles")
    lines.append("MinAlertLevel = warning")
    lines.append("")
    lines.append("[*.{md,mdx,html}]")
    lines.append("BasedOnStyles = COSGrid")
    lines.append("")
    for glob in allow_in_globs:
        lines.append(f"# allow_in exemption from registry: {glob}")
        lines.append(f"[{glob}]")
        lines.append("BasedOnStyles = COSGrid")
        lines.append("COSGrid.BrandRules = NO")
        lines.append("")

    with open(ini_path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines) + "\n")


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--registry", default="product-registry.yaml")
    parser.add_argument("--out", default="vale")
    args = parser.parse_args()

    try:
        registry = load_registry(args.registry)
    except FileNotFoundError:
        print(f"ERROR: registry not found at {args.registry}")
        sys.exit(1)

    out_dir = Path(args.out)
    styles_dir = out_dir / "styles" / "COSGrid"

    sub_style = build_substitution_style(registry)
    write_yaml(styles_dir / "ProductNames.yml", sub_style)

    prov_style = build_provisional_style(registry)
    write_yaml(styles_dir / "Provisional.yml", prov_style)

    brand_error, brand_warning = build_brand_rules_style(registry)
    write_yaml(styles_dir / "BrandRules.yml", brand_error)
    write_yaml(styles_dir / "CompanyName.yml", brand_warning)

    allow_in_globs = set()
    for rule in registry.get("brand", {}).get("global_rules", []) or []:
        for glob in rule.get("allow_in", []) or []:
            allow_in_globs.add(glob)

    write_vale_ini(out_dir, content_dirs=None, allow_in_globs=sorted(allow_in_globs))

    print(f"Generated Vale styles in {styles_dir}/")
    print(f"  ProductNames.yml : {len(sub_style['swap'])} substitution rules (error)")
    print(f"  Provisional.yml  : {len(prov_style['tokens'])} provisional terms (warning)")
    print(f"  BrandRules.yml   : {len(brand_error['tokens'])} forbidden brand terms (error)")
    print(f"  CompanyName.yml  : {len(brand_warning['tokens'])} company-name terms (warning)")
    print(f"Generated {out_dir}/.vale.ini")
    print()
    print("Next: cd into your content repo root, copy the vale/ folder in, then run:")
    print(f"  vale --config={args.out}/.vale.ini <path-to-content>")


if __name__ == "__main__":
    main()
